version: '3'
services:
  db:
    build: ./db
    ports:
      - '27017:27017'
  product-server:
    build: .
    links:
      - db
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=db:27017/test