version: '3'
services:
  db:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
  product-server:
    build: .
    depends_on:
      - db
    ports:
      - '5000:5000'